name: "WebP Optimizer Actions"
author: "Nemea"
description: "Compresses Images for the Web"

inputs:
  githubToken:
    description: "GitHub Token"
    required: true

  webpQuality:
    description: "WEBP quality level"
    required: false
    default: "80"

  ignorePaths:
    description: "Paths to ignore during search"
    required: false
    default: "node_modules/**"

runs:
  using: "docker"
  image: "docker://calibreapp/github-webp-optimizer"

branding:
  icon: "image"
  color: "green"
